#ifndef HINAPE_GAS_HINA_VOLUMEPARTICLEEMITTER_H
#define HINAPE_GAS_HINA_VOLUMEPARTICLEEMITTER_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		VolumeParticleEmitter,
		HINA_GETSET_PARAMETER(FluidDomain, GETSET_DATA_FUNCS_V3)
		HINA_GETSET_PARAMETER(TargetSpacing, GETSET_DATA_FUNCS_F)
		HINA_GETSET_PARAMETER(Jitter, GETSET_DATA_FUNCS_F)
		HINA_GETSET_PARAMETER(MaxNumOfParticles, GETSET_DATA_FUNCS_I)
		HINA_GETSET_PARAMETER(IsOneShot, GETSET_DATA_FUNCS_B)
		HINA_GETSET_PARAMETER(IsEmitterMove, GETSET_DATA_FUNCS_B)

		bool Emitted;
		int EmittedParticles;
)

#endif //HINAPE_GAS_HINA_VOLUMEPARTICLEEMITTER_H
