#ifndef HINAPE_GAS_HINA_SEMIIMPLICITEULER_H
#define HINAPE_GAS_HINA_SEMIIMPLICITEULER_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		SemiImplicitEuler,
)

#endif //HINAPE_GAS_HINA_SEMIIMPLICITEULER_H
