#ifndef HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H
#define HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H

#include <Common/SIM_Hina_Generator.h>

SIM_HINA_GEOMETRY_CLASS(
		Akinci2012BoundaryParticles,
)

#endif //HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H
