#ifndef HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H
#define HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H

#include <Common/SIM_Hina_Particles.h>

SIM_HINA_DERIVED_GEOMETRY_CLASS(
		Akinci2012BoundaryParticles,
		Particles,
		void Commit() override;
)

#endif //HINAPE_SIM_HINA_AKINCI2012BOUNDARYPARTICLES_H
