#ifndef HINAPE_GAS_HINA_BUILDNEIGHBORLISTS_H
#define HINAPE_GAS_HINA_BUILDNEIGHBORLISTS_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		BuildNeighborLists,
		HINA_GETSET_PARAMETER(KernelRadius, GETSET_DATA_FUNCS_F)
		HINA_GETSET_PARAMETER(Backend, GETSET_DATA_FUNCS_I)
)

#endif //HINAPE_HOUDINI_GAS_HINA_BUILDNEIGHBORLISTS_H
