#ifndef HINAPE_HOUDINI_GAS_HINA_UPDATEVOLUME_H
#define HINAPE_HOUDINI_GAS_HINA_UPDATEVOLUME_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		UpdateVolume,
)

#endif //HINAPE_HOUDINI_GAS_HINA_UPDATEVOLUME_H
