#ifndef HINAPE_GAS_HINA_UPDATEDENSITYAKINCI_H
#define HINAPE_GAS_HINA_UPDATEDENSITYAKINCI_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		UpdateDensityAkinci,
		HINA_GETSET_PARAMETER(Kernel, GETSET_DATA_FUNCS_I)
)

#endif //HINAPE_GAS_HINA_UPDATEDENSITYAKINCI_H
