#ifndef HINAPE_GAS_HINA_DFSPHSOLVER_H
#define HINAPE_GAS_HINA_DFSPHSOLVER_H

#include <Common/SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		DFSPHSolver,
)

#endif //HINAPE_GAS_HINA_DFSPHSOLVER_H
