#ifndef HINAPE_GAS_HINA_DFSPHSOLVER_H
#define HINAPE_GAS_HINA_DFSPHSOLVER_H

#include <SIM_Hina_Generator.h>

class SIM_Hina_DFSPHParticles;

GAS_HINA_SUBSOLVER_CLASS(
		DFSPHSolver,
)

#endif //HINAPE_GAS_HINA_DFSPHSOLVER_H
