#ifndef HINAPE_GAS_HINA_COLLISIONSOLVE_H
#define HINAPE_GAS_HINA_COLLISIONSOLVE_H

#include <Common/SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		CollisionSolve,
)

#endif //HINAPE_GAS_HINA_COLLISIONSOLVE_H
