#ifndef HINAPE_GAS_HINA_GRIDEXTERNALFORCE_H
#define HINAPE_GAS_HINA_GRIDEXTERNALFORCE_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		GridExternalForce,
		HINA_GETSET_PARAMETER(Gravity, GETSET_DATA_FUNCS_F)
		HINA_GETSET_PARAMETER(DensityFactor, GETSET_DATA_FUNCS_F)
		HINA_GETSET_PARAMETER(TemperatureFactor, GETSET_DATA_FUNCS_F)
)

#endif //HINAPE_GAS_HINA_GRIDEXTERNALFORCE_H
