#ifndef HINAPE_GAS_HINA_GRIDDIFFUSION_H
#define HINAPE_GAS_HINA_GRIDDIFFUSION_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		GridDiffusion,
		HINA_GETSET_PARAMETER(Diffusion, GETSET_DATA_FUNCS_F)
)

#endif //HINAPE_GAS_HINA_GRIDDIFFUSION_H
