#ifndef HINAPE_GAS_HINA_GRIDBUILDMARKER_H
#define HINAPE_GAS_HINA_GRIDBUILDMARKER_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		GridBuildMarker,
)

#endif //HINAPE_GAS_HINA_GRIDBUILDMARKER_H
