#ifndef HINAPE_GAS_HINA_GRIDBOUNDARYSOLVER_H
#define HINAPE_GAS_HINA_GRIDBOUNDARYSOLVER_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		GridBoundarySolver,
		HINA_GETSET_PARAMETER(Iter, GETSET_DATA_FUNCS_I)
)

#endif //HINAPE_GAS_HINA_GRIDBOUNDARYSOLVER_H
