#ifndef HINAPE_GAS_HINA_GRAVITYFORCE_H
#define HINAPE_GAS_HINA_GRAVITYFORCE_H

#include <SIM_Hina_Generator.h>

GAS_HINA_SUBSOLVER_CLASS(
		GravityForce,
		HINA_GETSET_PARAMETER(Gravity, GETSET_DATA_FUNCS_V3)
)

#endif //HINAPE_GAS_HINA_GRAVITYFORCE_H
